services:
  api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      TRAINDER_DO_NOT_USE_DOTENV: true
      MONGO_URI: mongodb://root:password@trainder-mongo:27017
      MONGO_DATABASE_NAME: trainder
      TOKEN_HOUR_LIFESPAN: 1
      API_SECRET: YOUR_API_SECRET
      INIT_ROOT_PASSWORD: YOUR_ROOT_PASSWORD
      OMISE_PUBLIC_KEY: OMISE_PUBKEY
      OMISE_SECRET_KEY: OMISE_SECKEY

  database:
    image: mongo:6.0.4-jammy
    container_name: trainder-mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      MONGO_INITDB_DATABASE: trainder
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

networks:
  backend: {}
