# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Go Project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 18.x

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          TRAINDER_DO_NOT_USE_DOTENV: true
          MONGO_URI: mongodb://localhost:27017
          MONGO_DATABASE_NAME: trainder
          TOKEN_HOUR_LIFESPAN: 24
          API_SECRET: api_secret
          INIT_ROOT_PASSWORD: password
